name: "Test Suite: core"

on:
  pull_request:
    paths:
      - 'core/**'
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    if: github.repository == 'cutenode/nodevu'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [current, lts/*, lts/-1]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install most recent npm
      run: npm install -g npm
    - name: Run npm install -w core
      run: npm install -w core
    - name: Run npm test -w core
      run: npm test -w core
    - name: 'Run npm run test:update and npm test -w core'
      run: npm run test:update && npm test -w core